name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  generateBadge:
    name: GenerateBadge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - name: Get Coverage for badge
        run: |
          SUMMARY="$(npm test -- --silent --coverage --coverageReporters='text-summary' | tail -4 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          echo "COVERAGE_COLOR=$(([[ ${TOKENS[2]%%.*} -ge 80 ]] && echo "green") || ([[ ${TOKENS[2]%%.*} -ge 50 ]] && echo "yellow") || echo "red")" >> $GITHUB_ENV
          ./bin/run ./src -t JSON | jq -r '.summaries | (."LogicalLineOfCode(Average per method)".value|tostring) + " " + (."CognitiveComplexity(Max)".value|tostring) + " " + (."Maintainability(Min)".value|tostring)' > sabik_result.txt
          SUMMARY=$(cat ./sabik_result.txt)
          TOKENS=($SUMMARY)
          echo "LINE_OF_CODE=$(printf "%.2f\n" ${TOKENS[0]})" >> $GITHUB_ENV
          echo "LINE_OF_CODE_COLOR=$(([[ ${TOKENS[0]%%.*} -le 15 ]] && echo "green") || ([[ ${TOKENS[0]%%.*} -le 20 ]] && echo "yellow") || echo "red")" >> $GITHUB_ENV
          echo "COGNITIVE_COMPLEXITY=$(printf "%.2f\n" ${TOKENS[1]})" >> $GITHUB_ENV
          echo "COGNITIVE_COMPLEXITY_COLOR=$(([[ ${TOKENS[1]%%.*} -le 8 ]] && echo "green") || echo "red")" >> $GITHUB_ENV
          echo "MAINTAINABILITY=$(printf "%.2f\n" ${TOKENS[2]})" >> $GITHUB_ENV
          echo "MAINTAINABILITY_COLOR=$(([[ ${TOKENS[2]%%.*} -ge 80 ]] && echo "green") || ([[ ${TOKENS[2]%%.*} -ge 50 ]] && echo "yellow") || echo "red")" >> $GITHUB_ENV
          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

      - name: Create the Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 32248b8c823155bb09711c7a5b960d3d
          filename: sabik_coverage_${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COVERAGE_COLOR }}
          namedLogo: jest

      - name: Create the LineOfCode Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 32248b8c823155bb09711c7a5b960d3d
          filename: sabik_line_of_code_${{ env.BRANCH }}.json
          label: LogicalLineOfCode(Average per method)
          message: ${{ env.LINE_OF_CODE }}
          color: ${{ env.LINE_OF_CODE_COLOR }}

      - name: Create the CognitiveComplexity Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 32248b8c823155bb09711c7a5b960d3d
          filename: sabik_cognitive_complexity_${{ env.BRANCH }}.json
          label: CognitiveComplexity(Max)
          message: ${{ env.COGNITIVE_COMPLEXITY }}
          color: ${{ env.COGNITIVE_COMPLEXITY_COLOR }}

      - name: Create the Maintainability Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 32248b8c823155bb09711c7a5b960d3d
          filename: sabik_maintainability_${{ env.BRANCH }}.json
          label: Maintainability(Min)
          message: ${{ env.MAINTAINABILITY }}
          color: ${{ env.MAINTAINABILITY_COLOR }}
  deploy:
    name: Release
    needs: generateBadge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 21
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

